# Generated by Django 5.0 on 2023-12-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name_c',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='description_c',
            field=models.CharField(default='DEFAULT VALUE', max_length=100, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_c',
            field=models.CharField(default='DEFAULT VALUE', max_length=100, verbose_name='название'),
        ),
    ]
