# Generated by Django 5.0 on 2023-12-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_category_description_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price_for_one',
            field=models.CharField(default='DEFAULT VALUE', max_length=100, verbose_name='цена за штуку'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified_data',
            field=models.CharField(max_length=100, verbose_name='дата последнего изменения'),
        ),
    ]
