# Generated by Django 5.0 on 2024-01-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_price_for_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified_data',
            field=models.DateField(auto_now_add=True, verbose_name='дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_for_one',
            field=models.IntegerField(verbose_name='цена за штуку'),
        ),
    ]
