# Generated by Django 5.0 on 2024-01-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_modified_data',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='дата последнего изменения'),
        ),
    ]
