# Generated by Django 4.2 on 2024-01-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_version_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='название'),
        ),
    ]
